entrada = input('Digite algo : ')
print('Informações da Variável')
print('-> O tipo primitivo desta variável é : [{}]', type(entrada))
print('-> Tem apenas espaços?                 [{}]', entrada.isspace())
print('-> É um número?                        [{}]', entrada.isnumeric())
print('-> É alfabético?                       [{}]', entrada.isalpha())
print('-> É alfanumérico?                     [{}]', entrada.isalnum())
print('-> Está em maiúsculas?                 [{}]', entrada.isupper())
print('-> Está em minúsculas?                 [{}]', entrada.islower())
print('-> Está capitalizado?                  [{}]', entrada.istitle())
